-- Merge the snapshot Supabase project into this one.
--
-- Run against the APP project (ugghpsupgqycsnvssseo), in Supabase's SQL Editor.
-- Creates the three tables that only existed in the snapshot project
-- (czfsjrvngiojjjevmvtz) plus the storage bucket their files live in. The data
-- itself is copied separately; this only prepares the destination.
--
-- Column shapes are taken from the live rows in the snapshot project, so an
-- upsert from there lands without a cast.

-- ── daily_kpi ───────────────────────────────────────────────────────────────
-- One finished row per person per day. The unique key is (date, person_id),
-- which is what api/snapshot.js upserts on — without it the cron inserts a
-- duplicate every run instead of updating the day.
create table if not exists daily_kpi (
  id              bigint generated by default as identity primary key,
  date            date not null,
  person_id       text not null,
  person_name     text,
  role            text,
  team_lead       text,
  calls           integer default 0,
  inbound         integer default 0,
  outbound        integer default 0,
  missed          integer default 0,
  minutes         integer default 0,
  leads           integer default 0,
  discoveries     integer default 0,
  pres_booked     integer default 0,
  pres_completed  integer default 0,
  presentations   integer default 0,
  deals_closed    integer default 0,
  new_upfront     numeric default 0,
  future_upfront  numeric default 0,
  score           integer default 0,
  zone            text,
  on_leave        boolean default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (date, person_id)
);

-- History reads whole months at a time, always filtered by date.
create index if not exists daily_kpi_date_idx on daily_kpi (date);

-- ── holidays ────────────────────────────────────────────────────────────────
create table if not exists holidays (
  date          date primary key,
  name          text not null,
  closes_floor  boolean not null default false,
  note          text,
  updated_at    timestamptz not null default now()
);

-- ── tv_slides ───────────────────────────────────────────────────────────────
create table if not exists tv_slides (
  id            bigint generated by default as identity primary key,
  storage_path  text not null,
  label         text,
  sort_order    integer default 0,
  enabled       boolean not null default false,
  created_at    timestamptz not null default now()
);

-- ── Access ──────────────────────────────────────────────────────────────────
-- Same shape as the tables already in this project: the browser reads and
-- writes with the anon key, and the pages that can reach these tables are
-- already behind the Google sign-in gate.
alter table daily_kpi enable row level security;
alter table holidays  enable row level security;
alter table tv_slides enable row level security;

create policy "daily_kpi read"  on daily_kpi for select using (true);
create policy "daily_kpi write" on daily_kpi for all    using (true) with check (true);

create policy "holidays read"   on holidays  for select using (true);
create policy "holidays write"  on holidays  for all    using (true) with check (true);

create policy "tv_slides read"  on tv_slides for select using (true);
create policy "tv_slides write" on tv_slides for all    using (true) with check (true);

-- ── api_logs, while we are here ─────────────────────────────────────────────
-- This table has been in this project all along and has never held a row:
-- every insert is refused with "new row violates row-level security policy",
-- and the catch that stops logging from failing a request swallows it. Reads
-- were allowed, which is why the admin panel showed an empty list rather than
-- an error.
create policy "api_logs insert" on api_logs for insert with check (true);

-- ── Storage ─────────────────────────────────────────────────────────────────
-- The TV board's promo slides. Public, because the board loads them straight
-- from the CDN with no session.
insert into storage.buckets (id, name, public)
values ('tv-slides', 'tv-slides', true)
on conflict (id) do nothing;

create policy "tv-slides public read" on storage.objects
  for select using (bucket_id = 'tv-slides');
create policy "tv-slides write" on storage.objects
  for all using (bucket_id = 'tv-slides') with check (bucket_id = 'tv-slides');
